/*
 * Project name:
     firsttest
 * Generated by:
     Visual TFT
 * Date of creation
     11.07.2017
 * Time of creation
     18:39:37
 * Test configuration:
     MCU:             FT900
     Dev.Board:       Mikromedia_HMI_43_CTP
     Oscillator:      100000000 Hz
     SW:              mikroC PRO for FT90X
                      http://www.mikroe.com/mikroc/ft90x/
     Note:            Download FT812 library at
                      http://www.mikroe.com/visualtft/#FT812
                      Download (if using external memory storage) FAT32 library at
                      http://www.libstock.com/projects/view/108/fat32-library
 */

#include "firsttest_objects.h"

void main() {

  InitVTFTStack();

  while (1) {
    ProcessVTFTStack();
  }

}
